// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GitHubDiscovery is an autogenerated mock type for the GitHubDiscovery type
type GitHubDiscovery struct {
	mock.Mock
}

type GitHubDiscovery_Expecter struct {
	mock *mock.Mock
}

func (_m *GitHubDiscovery) EXPECT() *GitHubDiscovery_Expecter {
	return &GitHubDiscovery_Expecter{mock: &_m.Mock}
}

// GetEmailFromUsername provides a mock function with given fields: _a0, _a1
func (_m *GitHubDiscovery) GetEmailFromUsername(_a0 context.Context, _a1 []string) ([]string, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GitHubDiscovery_GetEmailFromUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmailFromUsername'
type GitHubDiscovery_GetEmailFromUsername_Call struct {
	*mock.Call
}

// GetEmailFromUsername is a helper method to define mock.On call
//  - _a0 context.Context
//  - _a1 []string
func (_e *GitHubDiscovery_Expecter) GetEmailFromUsername(_a0 interface{}, _a1 interface{}) *GitHubDiscovery_GetEmailFromUsername_Call {
	return &GitHubDiscovery_GetEmailFromUsername_Call{Call: _e.mock.On("GetEmailFromUsername", _a0, _a1)}
}

func (_c *GitHubDiscovery_GetEmailFromUsername_Call) Run(run func(_a0 context.Context, _a1 []string)) *GitHubDiscovery_GetEmailFromUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *GitHubDiscovery_GetEmailFromUsername_Call) Return(_a0 []string, _a1 error) *GitHubDiscovery_GetEmailFromUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetUsernameFromEmail provides a mock function with given fields: _a0, _a1
func (_m *GitHubDiscovery) GetUsernameFromEmail(_a0 context.Context, _a1 []string) ([]string, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GitHubDiscovery_GetUsernameFromEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsernameFromEmail'
type GitHubDiscovery_GetUsernameFromEmail_Call struct {
	*mock.Call
}

// GetUsernameFromEmail is a helper method to define mock.On call
//  - _a0 context.Context
//  - _a1 []string
func (_e *GitHubDiscovery_Expecter) GetUsernameFromEmail(_a0 interface{}, _a1 interface{}) *GitHubDiscovery_GetUsernameFromEmail_Call {
	return &GitHubDiscovery_GetUsernameFromEmail_Call{Call: _e.mock.On("GetUsernameFromEmail", _a0, _a1)}
}

func (_c *GitHubDiscovery_GetUsernameFromEmail_Call) Run(run func(_a0 context.Context, _a1 []string)) *GitHubDiscovery_GetUsernameFromEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *GitHubDiscovery_GetUsernameFromEmail_Call) Return(_a0 []string, _a1 error) *GitHubDiscovery_GetUsernameFromEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewGitHubDiscovery interface {
	mock.TestingT
	Cleanup(func())
}

// NewGitHubDiscovery creates a new instance of GitHubDiscovery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGitHubDiscovery(t mockConstructorTestingTNewGitHubDiscovery) *GitHubDiscovery {
	mock := &GitHubDiscovery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
