// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	github "github.com/google/go-github/v47/github"
	mock "github.com/stretchr/testify/mock"
)

// IGitHubTeam is an autogenerated mock type for the iGitHubTeam type
type IGitHubTeam struct {
	mock.Mock
}

type IGitHubTeam_Expecter struct {
	mock *mock.Mock
}

func (_m *IGitHubTeam) EXPECT() *IGitHubTeam_Expecter {
	return &IGitHubTeam_Expecter{mock: &_m.Mock}
}

// AddTeamMembershipBySlug provides a mock function with given fields: ctx, org, slug, user, opts
func (_m *IGitHubTeam) AddTeamMembershipBySlug(ctx context.Context, org string, slug string, user string, opts *github.TeamAddTeamMembershipOptions) (*github.Membership, *github.Response, error) {
	ret := _m.Called(ctx, org, slug, user, opts)

	var r0 *github.Membership
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *github.TeamAddTeamMembershipOptions) *github.Membership); ok {
		r0 = rf(ctx, org, slug, user, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Membership)
		}
	}

	var r1 *github.Response
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *github.TeamAddTeamMembershipOptions) *github.Response); ok {
		r1 = rf(ctx, org, slug, user, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, *github.TeamAddTeamMembershipOptions) error); ok {
		r2 = rf(ctx, org, slug, user, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IGitHubTeam_AddTeamMembershipBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTeamMembershipBySlug'
type IGitHubTeam_AddTeamMembershipBySlug_Call struct {
	*mock.Call
}

// AddTeamMembershipBySlug is a helper method to define mock.On call
//  - ctx context.Context
//  - org string
//  - slug string
//  - user string
//  - opts *github.TeamAddTeamMembershipOptions
func (_e *IGitHubTeam_Expecter) AddTeamMembershipBySlug(ctx interface{}, org interface{}, slug interface{}, user interface{}, opts interface{}) *IGitHubTeam_AddTeamMembershipBySlug_Call {
	return &IGitHubTeam_AddTeamMembershipBySlug_Call{Call: _e.mock.On("AddTeamMembershipBySlug", ctx, org, slug, user, opts)}
}

func (_c *IGitHubTeam_AddTeamMembershipBySlug_Call) Run(run func(ctx context.Context, org string, slug string, user string, opts *github.TeamAddTeamMembershipOptions)) *IGitHubTeam_AddTeamMembershipBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*github.TeamAddTeamMembershipOptions))
	})
	return _c
}

func (_c *IGitHubTeam_AddTeamMembershipBySlug_Call) Return(_a0 *github.Membership, _a1 *github.Response, _a2 error) *IGitHubTeam_AddTeamMembershipBySlug_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

// ListTeamMembersBySlug provides a mock function with given fields: ctx, org, slug, opts
func (_m *IGitHubTeam) ListTeamMembersBySlug(ctx context.Context, org string, slug string, opts *github.TeamListTeamMembersOptions) ([]*github.User, *github.Response, error) {
	ret := _m.Called(ctx, org, slug, opts)

	var r0 []*github.User
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *github.TeamListTeamMembersOptions) []*github.User); ok {
		r0 = rf(ctx, org, slug, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.User)
		}
	}

	var r1 *github.Response
	if rf, ok := ret.Get(1).(func(context.Context, string, string, *github.TeamListTeamMembersOptions) *github.Response); ok {
		r1 = rf(ctx, org, slug, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, *github.TeamListTeamMembersOptions) error); ok {
		r2 = rf(ctx, org, slug, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IGitHubTeam_ListTeamMembersBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTeamMembersBySlug'
type IGitHubTeam_ListTeamMembersBySlug_Call struct {
	*mock.Call
}

// ListTeamMembersBySlug is a helper method to define mock.On call
//  - ctx context.Context
//  - org string
//  - slug string
//  - opts *github.TeamListTeamMembersOptions
func (_e *IGitHubTeam_Expecter) ListTeamMembersBySlug(ctx interface{}, org interface{}, slug interface{}, opts interface{}) *IGitHubTeam_ListTeamMembersBySlug_Call {
	return &IGitHubTeam_ListTeamMembersBySlug_Call{Call: _e.mock.On("ListTeamMembersBySlug", ctx, org, slug, opts)}
}

func (_c *IGitHubTeam_ListTeamMembersBySlug_Call) Run(run func(ctx context.Context, org string, slug string, opts *github.TeamListTeamMembersOptions)) *IGitHubTeam_ListTeamMembersBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*github.TeamListTeamMembersOptions))
	})
	return _c
}

func (_c *IGitHubTeam_ListTeamMembersBySlug_Call) Return(_a0 []*github.User, _a1 *github.Response, _a2 error) *IGitHubTeam_ListTeamMembersBySlug_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

// RemoveTeamMembershipBySlug provides a mock function with given fields: ctx, org, slug, user
func (_m *IGitHubTeam) RemoveTeamMembershipBySlug(ctx context.Context, org string, slug string, user string) (*github.Response, error) {
	ret := _m.Called(ctx, org, slug, user)

	var r0 *github.Response
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *github.Response); ok {
		r0 = rf(ctx, org, slug, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, org, slug, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IGitHubTeam_RemoveTeamMembershipBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTeamMembershipBySlug'
type IGitHubTeam_RemoveTeamMembershipBySlug_Call struct {
	*mock.Call
}

// RemoveTeamMembershipBySlug is a helper method to define mock.On call
//  - ctx context.Context
//  - org string
//  - slug string
//  - user string
func (_e *IGitHubTeam_Expecter) RemoveTeamMembershipBySlug(ctx interface{}, org interface{}, slug interface{}, user interface{}) *IGitHubTeam_RemoveTeamMembershipBySlug_Call {
	return &IGitHubTeam_RemoveTeamMembershipBySlug_Call{Call: _e.mock.On("RemoveTeamMembershipBySlug", ctx, org, slug, user)}
}

func (_c *IGitHubTeam_RemoveTeamMembershipBySlug_Call) Run(run func(ctx context.Context, org string, slug string, user string)) *IGitHubTeam_RemoveTeamMembershipBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *IGitHubTeam_RemoveTeamMembershipBySlug_Call) Return(_a0 *github.Response, _a1 error) *IGitHubTeam_RemoveTeamMembershipBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewIGitHubTeam interface {
	mock.TestingT
	Cleanup(func())
}

// NewIGitHubTeam creates a new instance of IGitHubTeam. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIGitHubTeam(t mockConstructorTestingTNewIGitHubTeam) *IGitHubTeam {
	mock := &IGitHubTeam{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
