version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /packages/github
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /packages/google
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /packages/gosync
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /packages/opsgenie
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /packages/slack
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /packages/terraformcloud
    schedule:
      interval: daily
