version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /adapters/azuread
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /adapters/github
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /adapters/google
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /adapters/opsgenie
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /adapters/slack
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /adapters/terraformcloud
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /adapters/test
    schedule:
      interval: daily
