issues:
  exclude-rules:
    # Test functions tend to be quite long due to the large amount of fixtures & test data etc.
    - linters:
        - funlen
      path: _test\.go
      text: "is too long"
    # There's no need to wrap errors in a test.
    - linters:
        - wrapcheck
      path: _test\.go
      text: "error returned from external package is unwrapped"
    # Commonly used in tests, and using sentinel errors for this is overkill.
    - linters:
        - nilnil
      path: _test\.go
      text: " use a sentinel error instead"

linters:
  enable-all: true
  disable:
    # tmpfix - currently breaking things
    - musttag

    - depguard
    - exhaustruct
    - forcetypeassert
    - godox
    - gomoddirectives
    - gomodguard
    - ireturn

    # deprecated
    - testableexamples

    # disabled because of generics
    - rowserrcheck
    - wastedassign

linters-settings:
  gomoddirectives:
    replace-local: true

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/ovotech)
      - blank
      - dot
    skip-generated: true
    custom-order: true

  revive:
    confidence: 0.1
    severity: warning
    rules:
      - name: exported
        severity: error
        disabled: false
        arguments:
          - checkPrivateReceivers

run:
  timeout: "5m"
