linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustruct
    - exhaustivestruct # deprecated
    - forcetypeassert
    - gofumpt
    - golint # deprecated
    - gomodguard
    - gomoddirectives
    - ifshort # deprecated
    - interfacer # deprecated
    - ireturn
    - maligned # deprecated
    - nosnakecase # deprecated
    - rowserrcheck # disabled because of generics
    - scopelint # deprecated
    - structcheck # deprecated
    - testableexamples # deprecated
    - varcheck
    - wastedassign # disabled because of generics

linters-settings:
  gomoddirectives:
    replace-local: true

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/ovotech)
      - prefix(github.com/ovotech/go-sync)
      - blank
      - dot
    skip-generated: true
    custom-order: true
