with-expecter: True
disable-version-string: True
dir: "mocks/{{.PackageName}}"
packages:
  github.com/ovotech/go-sync/pkg/types:
    interfaces:
      Adapter:
  github.com/ovotech/go-sync/internal/proto:
    interfaces:
      AdapterClient:
