// Code generated by mockery. DO NOT EDIT.

package user

import (
	context "context"

	tfe "github.com/hashicorp/go-tfe"
	mock "github.com/stretchr/testify/mock"
)

// mockITeams is an autogenerated mock type for the iTeams type
type mockITeams struct {
	mock.Mock
}

type mockITeams_Expecter struct {
	mock *mock.Mock
}

func (_m *mockITeams) EXPECT() *mockITeams_Expecter {
	return &mockITeams_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, organization, options
func (_m *mockITeams) List(ctx context.Context, organization string, options *tfe.TeamListOptions) (*tfe.TeamList, error) {
	ret := _m.Called(ctx, organization, options)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *tfe.TeamList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *tfe.TeamListOptions) (*tfe.TeamList, error)); ok {
		return rf(ctx, organization, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *tfe.TeamListOptions) *tfe.TeamList); ok {
		r0 = rf(ctx, organization, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tfe.TeamList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *tfe.TeamListOptions) error); ok {
		r1 = rf(ctx, organization, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockITeams_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockITeams_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - organization string
//   - options *tfe.TeamListOptions
func (_e *mockITeams_Expecter) List(ctx interface{}, organization interface{}, options interface{}) *mockITeams_List_Call {
	return &mockITeams_List_Call{Call: _e.mock.On("List", ctx, organization, options)}
}

func (_c *mockITeams_List_Call) Run(run func(ctx context.Context, organization string, options *tfe.TeamListOptions)) *mockITeams_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*tfe.TeamListOptions))
	})
	return _c
}

func (_c *mockITeams_List_Call) Return(_a0 *tfe.TeamList, _a1 error) *mockITeams_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockITeams_List_Call) RunAndReturn(run func(context.Context, string, *tfe.TeamListOptions) (*tfe.TeamList, error)) *mockITeams_List_Call {
	_c.Call.Return(run)
	return _c
}

// newMockITeams creates a new instance of mockITeams. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockITeams(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockITeams {
	mock := &mockITeams{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
