// Code generated by mockery v2.14.1. DO NOT EDIT.

package team

import (
	context "context"

	tfe "github.com/hashicorp/go-tfe"
	mock "github.com/stretchr/testify/mock"
)

// mockITeams is an autogenerated mock type for the iTeams type
type mockITeams struct {
	mock.Mock
}

type mockITeams_Expecter struct {
	mock *mock.Mock
}

func (_m *mockITeams) EXPECT() *mockITeams_Expecter {
	return &mockITeams_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, organization, options
func (_m *mockITeams) Create(ctx context.Context, organization string, options tfe.TeamCreateOptions) (*tfe.Team, error) {
	ret := _m.Called(ctx, organization, options)

	var r0 *tfe.Team
	if rf, ok := ret.Get(0).(func(context.Context, string, tfe.TeamCreateOptions) *tfe.Team); ok {
		r0 = rf(ctx, organization, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tfe.Team)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, tfe.TeamCreateOptions) error); ok {
		r1 = rf(ctx, organization, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockITeams_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockITeams_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//  - ctx context.Context
//  - organization string
//  - options tfe.TeamCreateOptions
func (_e *mockITeams_Expecter) Create(ctx interface{}, organization interface{}, options interface{}) *mockITeams_Create_Call {
	return &mockITeams_Create_Call{Call: _e.mock.On("Create", ctx, organization, options)}
}

func (_c *mockITeams_Create_Call) Run(run func(ctx context.Context, organization string, options tfe.TeamCreateOptions)) *mockITeams_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(tfe.TeamCreateOptions))
	})
	return _c
}

func (_c *mockITeams_Create_Call) Return(_a0 *tfe.Team, _a1 error) *mockITeams_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Delete provides a mock function with given fields: ctx, teamID
func (_m *mockITeams) Delete(ctx context.Context, teamID string) error {
	ret := _m.Called(ctx, teamID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockITeams_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockITeams_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//  - ctx context.Context
//  - teamID string
func (_e *mockITeams_Expecter) Delete(ctx interface{}, teamID interface{}) *mockITeams_Delete_Call {
	return &mockITeams_Delete_Call{Call: _e.mock.On("Delete", ctx, teamID)}
}

func (_c *mockITeams_Delete_Call) Run(run func(ctx context.Context, teamID string)) *mockITeams_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockITeams_Delete_Call) Return(_a0 error) *mockITeams_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

// List provides a mock function with given fields: ctx, organization, options
func (_m *mockITeams) List(ctx context.Context, organization string, options *tfe.TeamListOptions) (*tfe.TeamList, error) {
	ret := _m.Called(ctx, organization, options)

	var r0 *tfe.TeamList
	if rf, ok := ret.Get(0).(func(context.Context, string, *tfe.TeamListOptions) *tfe.TeamList); ok {
		r0 = rf(ctx, organization, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tfe.TeamList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *tfe.TeamListOptions) error); ok {
		r1 = rf(ctx, organization, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockITeams_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockITeams_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//  - ctx context.Context
//  - organization string
//  - options *tfe.TeamListOptions
func (_e *mockITeams_Expecter) List(ctx interface{}, organization interface{}, options interface{}) *mockITeams_List_Call {
	return &mockITeams_List_Call{Call: _e.mock.On("List", ctx, organization, options)}
}

func (_c *mockITeams_List_Call) Run(run func(ctx context.Context, organization string, options *tfe.TeamListOptions)) *mockITeams_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*tfe.TeamListOptions))
	})
	return _c
}

func (_c *mockITeams_List_Call) Return(_a0 *tfe.TeamList, _a1 error) *mockITeams_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTnewMockITeams interface {
	mock.TestingT
	Cleanup(func())
}

// newMockITeams creates a new instance of mockITeams. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockITeams(t mockConstructorTestingTnewMockITeams) *mockITeams {
	mock := &mockITeams{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
