// Code generated by mockery. DO NOT EDIT.

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/ovotech/go-sync/internal/proto"
)

// MockAdapterClient is an autogenerated mock type for the AdapterClient type
type MockAdapterClient struct {
	mock.Mock
}

type MockAdapterClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapterClient) EXPECT() *MockAdapterClient_Expecter {
	return &MockAdapterClient_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, in, opts
func (_m *MockAdapterClient) Add(ctx context.Context, in *proto.Add_Request, opts ...grpc.CallOption) (*proto.Add_Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *proto.Add_Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.Add_Request, ...grpc.CallOption) (*proto.Add_Response, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.Add_Request, ...grpc.CallOption) *proto.Add_Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Add_Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.Add_Request, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapterClient_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockAdapterClient_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.Add_Request
//   - opts ...grpc.CallOption
func (_e *MockAdapterClient_Expecter) Add(ctx interface{}, in interface{}, opts ...interface{}) *MockAdapterClient_Add_Call {
	return &MockAdapterClient_Add_Call{Call: _e.mock.On("Add",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAdapterClient_Add_Call) Run(run func(ctx context.Context, in *proto.Add_Request, opts ...grpc.CallOption)) *MockAdapterClient_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.Add_Request), variadicArgs...)
	})
	return _c
}

func (_c *MockAdapterClient_Add_Call) Return(_a0 *proto.Add_Response, _a1 error) *MockAdapterClient_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapterClient_Add_Call) RunAndReturn(run func(context.Context, *proto.Add_Request, ...grpc.CallOption) (*proto.Add_Response, error)) *MockAdapterClient_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, in, opts
func (_m *MockAdapterClient) Get(ctx context.Context, in *proto.Get_Request, opts ...grpc.CallOption) (*proto.Get_Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *proto.Get_Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.Get_Request, ...grpc.CallOption) (*proto.Get_Response, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.Get_Request, ...grpc.CallOption) *proto.Get_Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Get_Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.Get_Request, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapterClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAdapterClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.Get_Request
//   - opts ...grpc.CallOption
func (_e *MockAdapterClient_Expecter) Get(ctx interface{}, in interface{}, opts ...interface{}) *MockAdapterClient_Get_Call {
	return &MockAdapterClient_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAdapterClient_Get_Call) Run(run func(ctx context.Context, in *proto.Get_Request, opts ...grpc.CallOption)) *MockAdapterClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.Get_Request), variadicArgs...)
	})
	return _c
}

func (_c *MockAdapterClient_Get_Call) Return(_a0 *proto.Get_Response, _a1 error) *MockAdapterClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapterClient_Get_Call) RunAndReturn(run func(context.Context, *proto.Get_Request, ...grpc.CallOption) (*proto.Get_Response, error)) *MockAdapterClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function with given fields: ctx, in, opts
func (_m *MockAdapterClient) Init(ctx context.Context, in *proto.Init_Request, opts ...grpc.CallOption) (*proto.Init_Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 *proto.Init_Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.Init_Request, ...grpc.CallOption) (*proto.Init_Response, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.Init_Request, ...grpc.CallOption) *proto.Init_Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Init_Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.Init_Request, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapterClient_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockAdapterClient_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.Init_Request
//   - opts ...grpc.CallOption
func (_e *MockAdapterClient_Expecter) Init(ctx interface{}, in interface{}, opts ...interface{}) *MockAdapterClient_Init_Call {
	return &MockAdapterClient_Init_Call{Call: _e.mock.On("Init",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAdapterClient_Init_Call) Run(run func(ctx context.Context, in *proto.Init_Request, opts ...grpc.CallOption)) *MockAdapterClient_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.Init_Request), variadicArgs...)
	})
	return _c
}

func (_c *MockAdapterClient_Init_Call) Return(_a0 *proto.Init_Response, _a1 error) *MockAdapterClient_Init_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapterClient_Init_Call) RunAndReturn(run func(context.Context, *proto.Init_Request, ...grpc.CallOption) (*proto.Init_Response, error)) *MockAdapterClient_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx, in, opts
func (_m *MockAdapterClient) Remove(ctx context.Context, in *proto.Remove_Request, opts ...grpc.CallOption) (*proto.Remove_Response, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 *proto.Remove_Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.Remove_Request, ...grpc.CallOption) (*proto.Remove_Response, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.Remove_Request, ...grpc.CallOption) *proto.Remove_Response); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Remove_Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.Remove_Request, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapterClient_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockAdapterClient_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.Remove_Request
//   - opts ...grpc.CallOption
func (_e *MockAdapterClient_Expecter) Remove(ctx interface{}, in interface{}, opts ...interface{}) *MockAdapterClient_Remove_Call {
	return &MockAdapterClient_Remove_Call{Call: _e.mock.On("Remove",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAdapterClient_Remove_Call) Run(run func(ctx context.Context, in *proto.Remove_Request, opts ...grpc.CallOption)) *MockAdapterClient_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.Remove_Request), variadicArgs...)
	})
	return _c
}

func (_c *MockAdapterClient_Remove_Call) Return(_a0 *proto.Remove_Response, _a1 error) *MockAdapterClient_Remove_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapterClient_Remove_Call) RunAndReturn(run func(context.Context, *proto.Remove_Request, ...grpc.CallOption) (*proto.Remove_Response, error)) *MockAdapterClient_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdapterClient creates a new instance of MockAdapterClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapterClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapterClient {
	mock := &MockAdapterClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
