// Code generated by mockery. DO NOT EDIT.

package membership

import (
	context "context"

	tfe "github.com/hashicorp/go-tfe"
	mock "github.com/stretchr/testify/mock"
)

// mockIOrganizationMemberships is an autogenerated mock type for the iOrganizationMemberships type
type mockIOrganizationMemberships struct {
	mock.Mock
}

type mockIOrganizationMemberships_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIOrganizationMemberships) EXPECT() *mockIOrganizationMemberships_Expecter {
	return &mockIOrganizationMemberships_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, organization, options
func (_m *mockIOrganizationMemberships) Create(ctx context.Context, organization string, options tfe.OrganizationMembershipCreateOptions) (*tfe.OrganizationMembership, error) {
	ret := _m.Called(ctx, organization, options)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *tfe.OrganizationMembership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, tfe.OrganizationMembershipCreateOptions) (*tfe.OrganizationMembership, error)); ok {
		return rf(ctx, organization, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, tfe.OrganizationMembershipCreateOptions) *tfe.OrganizationMembership); ok {
		r0 = rf(ctx, organization, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tfe.OrganizationMembership)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, tfe.OrganizationMembershipCreateOptions) error); ok {
		r1 = rf(ctx, organization, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIOrganizationMemberships_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockIOrganizationMemberships_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - organization string
//   - options tfe.OrganizationMembershipCreateOptions
func (_e *mockIOrganizationMemberships_Expecter) Create(ctx interface{}, organization interface{}, options interface{}) *mockIOrganizationMemberships_Create_Call {
	return &mockIOrganizationMemberships_Create_Call{Call: _e.mock.On("Create", ctx, organization, options)}
}

func (_c *mockIOrganizationMemberships_Create_Call) Run(run func(ctx context.Context, organization string, options tfe.OrganizationMembershipCreateOptions)) *mockIOrganizationMemberships_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(tfe.OrganizationMembershipCreateOptions))
	})
	return _c
}

func (_c *mockIOrganizationMemberships_Create_Call) Return(_a0 *tfe.OrganizationMembership, _a1 error) *mockIOrganizationMemberships_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIOrganizationMemberships_Create_Call) RunAndReturn(run func(context.Context, string, tfe.OrganizationMembershipCreateOptions) (*tfe.OrganizationMembership, error)) *mockIOrganizationMemberships_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, organizationMembershipID
func (_m *mockIOrganizationMemberships) Delete(ctx context.Context, organizationMembershipID string) error {
	ret := _m.Called(ctx, organizationMembershipID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, organizationMembershipID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockIOrganizationMemberships_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockIOrganizationMemberships_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationMembershipID string
func (_e *mockIOrganizationMemberships_Expecter) Delete(ctx interface{}, organizationMembershipID interface{}) *mockIOrganizationMemberships_Delete_Call {
	return &mockIOrganizationMemberships_Delete_Call{Call: _e.mock.On("Delete", ctx, organizationMembershipID)}
}

func (_c *mockIOrganizationMemberships_Delete_Call) Run(run func(ctx context.Context, organizationMembershipID string)) *mockIOrganizationMemberships_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockIOrganizationMemberships_Delete_Call) Return(_a0 error) *mockIOrganizationMemberships_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIOrganizationMemberships_Delete_Call) RunAndReturn(run func(context.Context, string) error) *mockIOrganizationMemberships_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, organization, options
func (_m *mockIOrganizationMemberships) List(ctx context.Context, organization string, options *tfe.OrganizationMembershipListOptions) (*tfe.OrganizationMembershipList, error) {
	ret := _m.Called(ctx, organization, options)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *tfe.OrganizationMembershipList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *tfe.OrganizationMembershipListOptions) (*tfe.OrganizationMembershipList, error)); ok {
		return rf(ctx, organization, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *tfe.OrganizationMembershipListOptions) *tfe.OrganizationMembershipList); ok {
		r0 = rf(ctx, organization, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tfe.OrganizationMembershipList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *tfe.OrganizationMembershipListOptions) error); ok {
		r1 = rf(ctx, organization, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIOrganizationMemberships_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockIOrganizationMemberships_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - organization string
//   - options *tfe.OrganizationMembershipListOptions
func (_e *mockIOrganizationMemberships_Expecter) List(ctx interface{}, organization interface{}, options interface{}) *mockIOrganizationMemberships_List_Call {
	return &mockIOrganizationMemberships_List_Call{Call: _e.mock.On("List", ctx, organization, options)}
}

func (_c *mockIOrganizationMemberships_List_Call) Run(run func(ctx context.Context, organization string, options *tfe.OrganizationMembershipListOptions)) *mockIOrganizationMemberships_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*tfe.OrganizationMembershipListOptions))
	})
	return _c
}

func (_c *mockIOrganizationMemberships_List_Call) Return(_a0 *tfe.OrganizationMembershipList, _a1 error) *mockIOrganizationMemberships_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIOrganizationMemberships_List_Call) RunAndReturn(run func(context.Context, string, *tfe.OrganizationMembershipListOptions) (*tfe.OrganizationMembershipList, error)) *mockIOrganizationMemberships_List_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: ctx, organizationMembershipID
func (_m *mockIOrganizationMemberships) Read(ctx context.Context, organizationMembershipID string) (*tfe.OrganizationMembership, error) {
	ret := _m.Called(ctx, organizationMembershipID)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *tfe.OrganizationMembership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*tfe.OrganizationMembership, error)); ok {
		return rf(ctx, organizationMembershipID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *tfe.OrganizationMembership); ok {
		r0 = rf(ctx, organizationMembershipID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tfe.OrganizationMembership)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, organizationMembershipID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIOrganizationMemberships_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type mockIOrganizationMemberships_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationMembershipID string
func (_e *mockIOrganizationMemberships_Expecter) Read(ctx interface{}, organizationMembershipID interface{}) *mockIOrganizationMemberships_Read_Call {
	return &mockIOrganizationMemberships_Read_Call{Call: _e.mock.On("Read", ctx, organizationMembershipID)}
}

func (_c *mockIOrganizationMemberships_Read_Call) Run(run func(ctx context.Context, organizationMembershipID string)) *mockIOrganizationMemberships_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockIOrganizationMemberships_Read_Call) Return(_a0 *tfe.OrganizationMembership, _a1 error) *mockIOrganizationMemberships_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockIOrganizationMemberships_Read_Call) RunAndReturn(run func(context.Context, string) (*tfe.OrganizationMembership, error)) *mockIOrganizationMemberships_Read_Call {
	_c.Call.Return(run)
	return _c
}

// newMockIOrganizationMemberships creates a new instance of mockIOrganizationMemberships. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIOrganizationMemberships(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIOrganizationMemberships {
	mock := &mockIOrganizationMemberships{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
