// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

type Logger_Expecter struct {
	mock *mock.Mock
}

func (_m *Logger) EXPECT() *Logger_Expecter {
	return &Logger_Expecter{mock: &_m.Mock}
}

// Printf provides a mock function with given fields: format, v
func (_m *Logger) Printf(format string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// Logger_Printf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Printf'
type Logger_Printf_Call struct {
	*mock.Call
}

// Printf is a helper method to define mock.On call
//   - format string
//   - v ...interface{}
func (_e *Logger_Expecter) Printf(format interface{}, v ...interface{}) *Logger_Printf_Call {
	return &Logger_Printf_Call{Call: _e.mock.On("Printf",
		append([]interface{}{format}, v...)...)}
}

func (_c *Logger_Printf_Call) Run(run func(format string, v ...interface{})) *Logger_Printf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Logger_Printf_Call) Return() *Logger_Printf_Call {
	_c.Call.Return()
	return _c
}

// Println provides a mock function with given fields: v
func (_m *Logger) Println(v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// Logger_Println_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Println'
type Logger_Println_Call struct {
	*mock.Call
}

// Println is a helper method to define mock.On call
//   - v ...interface{}
func (_e *Logger_Expecter) Println(v ...interface{}) *Logger_Println_Call {
	return &Logger_Println_Call{Call: _e.mock.On("Println",
		append([]interface{}{}, v...)...)}
}

func (_c *Logger_Println_Call) Run(run func(v ...interface{})) *Logger_Println_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Logger_Println_Call) Return() *Logger_Println_Call {
	_c.Call.Return()
	return _c
}

type mockConstructorTestingTNewLogger interface {
	mock.TestingT
	Cleanup(func())
}

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLogger(t mockConstructorTestingTNewLogger) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
