// Code generated by mockery. DO NOT EDIT.

package saml

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockIGitHubV4Saml is an autogenerated mock type for the iGitHubV4Saml type
type mockIGitHubV4Saml struct {
	mock.Mock
}

type mockIGitHubV4Saml_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIGitHubV4Saml) EXPECT() *mockIGitHubV4Saml_Expecter {
	return &mockIGitHubV4Saml_Expecter{mock: &_m.Mock}
}

// Query provides a mock function with given fields: ctx, q, variables
func (_m *mockIGitHubV4Saml) Query(ctx context.Context, q interface{}, variables map[string]interface{}) error {
	ret := _m.Called(ctx, q, variables)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, map[string]interface{}) error); ok {
		r0 = rf(ctx, q, variables)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockIGitHubV4Saml_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type mockIGitHubV4Saml_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - q interface{}
//   - variables map[string]interface{}
func (_e *mockIGitHubV4Saml_Expecter) Query(ctx interface{}, q interface{}, variables interface{}) *mockIGitHubV4Saml_Query_Call {
	return &mockIGitHubV4Saml_Query_Call{Call: _e.mock.On("Query", ctx, q, variables)}
}

func (_c *mockIGitHubV4Saml_Query_Call) Run(run func(ctx context.Context, q interface{}, variables map[string]interface{})) *mockIGitHubV4Saml_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *mockIGitHubV4Saml_Query_Call) Return(_a0 error) *mockIGitHubV4Saml_Query_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockIGitHubV4Saml_Query_Call) RunAndReturn(run func(context.Context, interface{}, map[string]interface{}) error) *mockIGitHubV4Saml_Query_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockIGitHubV4Saml interface {
	mock.TestingT
	Cleanup(func())
}

// newMockIGitHubV4Saml creates a new instance of mockIGitHubV4Saml. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockIGitHubV4Saml(t mockConstructorTestingTnewMockIGitHubV4Saml) *mockIGitHubV4Saml {
	mock := &mockIGitHubV4Saml{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
