name: docs

on:
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: gomarkdoc
        id: gomarkdoc
        run: |
          go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest
          ~/go/bin/gomarkdoc --output doc.md ./pkg/...
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: gomarkdoc
          author_email: gomarkdoc@no-reply.com
          message: 'Update Documentation'
          add: 'doc.md'
