name: lint

on:
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: |
            *.sum
            **/*.sum
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
      - name: Generate source files
        run: task generate
      - name: Fix linter errors
        run: task lint:fix
      - name: Lint all source code
        run: task lint
      - name: Check for changes
        id: check-changed-files
        uses: tj-actions/verify-changed-files@v20
        with:
          files: |
            *
      - name: Diff
        if: steps.check-changed-files.outputs.files_changed == 'true'
        run: git diff
      - name: Fail if code needs linting
        if: steps.check-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.check-changed-files.outputs.changed_files }}"
          echo "Run task generate lint:fix to attempt to fix linter errors."
          exit 1
