name: mockery

on:
  pull_request:
    branches:
      - main

jobs:
  mockery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: mockery
        id: mockery
        run: |
          go install github.com/vektra/mockery/v2@latest
          ~/go/bin/mockery --all --exported --with-expecter --output "./internal/mocks"
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: mockery
          author_email: mockery@no-reply.com
          message: 'Update Mocks'
          add: 'mocks/*'
