name: mockery

on:
  pull_request:
    branches:
      - main

jobs:
  mockery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: mockery
        id: mockery
        run: |
          rm -f ./internal/mocks
          go install github.com/vektra/mockery/v2@latest
          ~/go/bin/mockery --all --exported --with-expecter --output "./internal/mocks"
      - name: Check for changes
        id: check-changed-files
        uses: tj-actions/verify-changed-files@v11.1
        if: github.event_name == 'pull_request'
        with:
          files : |
            ./internal/mocks
      - name: Fail on changes
        if: steps.check-changed-files.outputs.files_changed == 'true'
        run: |
          exit 1
