name: mockery

on:
  push:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  mockery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: mockery
        id: mockery
        run: |
          go install github.com/vektra/mockery/v2@latest
          ~/go/bin/mockery --all --exported --with-expecter --output "./internal/mocks"
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'internal/mocks/*'
          message: 'Update Mocks'
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
