name: test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Install JUnit Reporter
        run: |
          go install github.com/jstemmer/go-junit-report@latest
      - name: Test
        run: go test -v 2>&1 -count=1 ./... | go-junit-report -set-exit-code > report.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "report.xml"
          pull_request_build: "commit"
          report_individual_runs: true
