name: test

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Install JUnit Reporter
        run: |
          go install github.com/jstemmer/go-junit-report@latest
      - name: Test
        run: go test -v 2>&1 -count=1 ./... | go-junit-report -set-exit-code > report.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "report.xml"
