name: test

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21]
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.work
          cache-dependency-path: |
            *.sum
            **/*.sum
      - uses: arduino/setup-task@v1
        with:
          version: 3.x
      - name: Run Go tests and generate report
        run: task tests:gotest:report
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results (Go ${{ matrix.go-version }})
          path: |
            report.xml
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Event File
          path: ${{ github.event_path }}
